// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroApi.Data;

#nullable disable

namespace SuperHeroApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperHeroApi.Models.SuperHero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Abilities")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("SuperHeros");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Abilities = "Web-slinging, Wall-crawling, Spider sense",
                            Description = "A young man with spider-like abilities",
                            FirstName = "Peter",
                            Health = 100,
                            HeroName = "Spider-Man",
                            LastName = "Parker",
                            Place = "New York",
                            Role = "Offensive",
                            Speed = 15.0,
                            Strength = 50
                        },
                        new
                        {
                            id = 2,
                            Abilities = "Flight, Energy blasts, Genius intellect",
                            Description = "A billionaire inventor and superhero",
                            FirstName = "Tony",
                            Health = 200,
                            HeroName = "Iron Man",
                            LastName = "Stark",
                            Place = "New York",
                            Role = "Offensive",
                            Speed = 10.5,
                            Strength = 75
                        },
                        new
                        {
                            id = 3,
                            Abilities = "Super strength, Enhanced endurance, Shield",
                            Description = "A super-soldier enhanced by a serum",
                            FirstName = "Steve",
                            Health = 150,
                            HeroName = "Captain America",
                            LastName = "Rogers",
                            Place = "Brooklyn, New York",
                            Role = "Defensive",
                            Speed = 12.0,
                            Strength = 80
                        },
                        new
                        {
                            id = 4,
                            Abilities = "Super strength, Flight, Lightning control",
                            Description = "The God of Thunder, wielder of Mjolnir",
                            FirstName = "Thor",
                            Health = 250,
                            HeroName = "Thor",
                            LastName = "Odinson",
                            Place = "Asgard",
                            Role = "Offensive",
                            Speed = 11.0,
                            Strength = 100
                        },
                        new
                        {
                            id = 5,
                            Abilities = "Super strength, Agility, Vibranium suit",
                            Description = "The king of Wakanda with enhanced physical abilities",
                            FirstName = "T'Challa",
                            Health = 175,
                            HeroName = "Black Panther",
                            LastName = "",
                            Place = "Wakanda",
                            Role = "Offensive",
                            Speed = 14.0,
                            Strength = 70
                        });
                });

            modelBuilder.Entity("SuperHeroApi.Models.Villain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Abilities")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<string>("VillainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Villain");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Abilities = "Glider, Pumpkin bombs, Super strength",
                            Description = "A dangerous foe with high-tech weapons",
                            FirstName = "Norman",
                            Health = 120,
                            LastName = "Osborn",
                            Place = "New York",
                            Role = "Offensive",
                            Speed = 10.0,
                            Strength = 70,
                            VillainName = "Green Goblin"
                        },
                        new
                        {
                            id = 2,
                            Abilities = "Super strength, Immortality, Reality manipulation",
                            Description = "The Mad Titan with a quest for universal power",
                            FirstName = "Thanos",
                            Health = 250,
                            LastName = "",
                            Place = "Titan",
                            Role = "Offensive",
                            Speed = 8.5,
                            Strength = 95,
                            VillainName = "Thanos"
                        },
                        new
                        {
                            id = 3,
                            Abilities = "Illusion casting, Shape-shifting, Magic",
                            Description = "The God of Mischief, brother of Thor",
                            FirstName = "Loki",
                            Health = 150,
                            LastName = "",
                            Place = "Asgard",
                            Role = "Support",
                            Speed = 13.0,
                            Strength = 50,
                            VillainName = "Loki"
                        },
                        new
                        {
                            id = 4,
                            Abilities = "Magic, Super intellect, Energy blasts",
                            Description = "A genius with vast technological and magical powers",
                            FirstName = "Victor",
                            Health = 175,
                            LastName = "Von Doom",
                            Place = "Latveria",
                            Role = "Offensive",
                            Speed = 10.0,
                            Strength = 80,
                            VillainName = "Doctor Doom"
                        },
                        new
                        {
                            id = 5,
                            Abilities = "Artificial intelligence, Super strength, Flight",
                            Description = "A rogue AI bent on global destruction",
                            FirstName = "Ultron",
                            Health = 200,
                            LastName = "",
                            Place = "Unknown",
                            Role = "Offensive",
                            Speed = 9.0,
                            Strength = 90,
                            VillainName = "Ultron"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
